sudo: false
language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install pytest
- pip install coveralls
script:
- py.test tests.py
deploy:
  provider: pypi
  user: dahoiv
  password:
    secure: vb4YvGT1+UAC8cEWx7kg4fjyGgmYDFrMgrhxnY4NOX9CLOWSU4+IiC3jsj5h9P6aNsIMcrsZPlgfk9qu8VTXigJ34ZI83eS29/2GYxomYrRMQLW5VUSYQBAgh1OPXX6QGqRu7zJdJzo0bRbSXdgf+YoZ6IqGuSKh/G5WwW3D/2c7RAUVqXvnhBd3wzbyKkeSWmTf94v6EzjspMQPAFTZtw/hF8yLH90ELsOQCj8yi9Q2u3DPhMO4cjWRVIRy6LlkXaA6WbRHdSGknbk2jiMEMOWx6D7NpA8T0tiUyF3NQyz4QLrA2aHTOjAtLZcmtY8v6hIr8Kfci1r9Oq9mBRby8BO67/w4njE/WZNXiyKAMt0EbE2uAy8KkfFaUP6/HeFjD+L/5auHesQoV+Ev3571v4ph3jVRylSrfQgQs3upxzqT9Hv+hsPbyux3kWFaNwBgAt6ZNyGEwOHpH/T7m6JyCWum4aUF10S9R/BT7uaceLSyWY5OkZ8zCRuBOlcvMKtO/AiQFgHrO0c8ADzr3v7FeV1qe7siA1CqvFziwcI/QGWq13HiaLQc64KHdGVqVGntjF8aE5iS70D/JXqEHhi58/6x9tuAcmqzllJIpt0FZ0sUrqb4liFteh+f7EzKKSSgCLOjaOTbmD+mWAmbgdQo5+MgyGF2t+Vcbv79co1a/lA=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: Danielhiversen/flux_led
